version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd backend
      - npm install
  build:
    commands:
      - echo "Build finished for backend"
artifacts:
  files:
    - '/*'
  base-directory: backend
